#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export LANG=ja_JP.UTF-8
export FZF_DEFAULT_OPTS="--layout=reverse --height=45%"
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES"
export ENHANCD_FILTER="fzf"
export GOENV_DISABLE_GOPATH=1
export GOPATH="$HOME/go"
export MYVIMRC="$HOME/.config/nvim/init.vim"
# export PATH="$(echo "$PATH" | sed -E -e 's;:/mnt/[^:]+;;g')"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# for vagrant
# if [[ -f /proc/sys/fs/binfmt_misc/WSLInterop ]]; then
#     export VAGRANT_WSL_WINDOWS_ACCESS_USER="whiteleaf"
#     export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
#     # export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH="/mnt/c/vagrant"
#     export PATH="$PATH:/mnt/c/Program Files/Oracle/VirtualBox"
#     export PATH="$PATH:/mnt/c/Windows/System32"
#     export PATH="$PATH:/mnt/c/Windows/System32/WindowsPowerShell/v1.0"
# fi
